---
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods: "*"
            allow-credentials: true
  application:
    name: "card-gateway"

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8073/eureka/"
server:
  port: 8000